### ISSUE TITLE
If svelte-apollo (and others) is a devDependency, how will it work in a production environment?

### ISSUE THREAD

**Issue by yokhen** [imCorfitz/sapper-w-svelte-apollo#8]
If svelte-apollo (from where the `setClient` method is taken) is a devDependency, then how will it work in a production environment? 

Yarn doesn't install devDependencies on production environments as far as I know.

Why does it need to be a devDependency??

**Comment by imCorfitz** [comment]
I haven't worked much with Svelte lately, but at the time of this development, Svelte is considered a compiler and development framework. Dev dependencies was a standard procedure, as packages are compiled to pure javascript at build rather than running as a stack og packages and libraries.
